"""empty message

Revision ID: 342320cea269
Revises: 4d2cb71247c0
Create Date: 2021-11-19 13:18:05.019810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342320cea269'
down_revision = '4d2cb71247c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('networth', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('networth', 'total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('networth', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('networth', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('networth', 'total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('networth', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
