"""empty message

Revision ID: 4d2cb71247c0
Revises: 67576a59ebf1
Create Date: 2021-11-07 10:41:22.367702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2cb71247c0'
down_revision = '67576a59ebf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('networth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('netWorth', sa.INTEGER(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('networth')
    # ### end Alembic commands ###
