"""empty message

Revision ID: 67576a59ebf1
Revises: 6c1e1663ac27
Create Date: 2021-11-07 10:30:31.413796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67576a59ebf1'
down_revision = '6c1e1663ac27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netWorth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
