"""empty message

Revision ID: 6c1e1663ac27
Revises: 863156fd02de
Create Date: 2021-11-02 17:27:26.764260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1e1663ac27'
down_revision = '863156fd02de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending', 'date')
    # ### end Alembic commands ###
