"""empty message

Revision ID: 863156fd02de
Revises: 7d004cefd497
Create Date: 2021-11-02 17:00:50.868996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863156fd02de'
down_revision = '7d004cefd497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spending', sa.Column('transaction_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spending', 'transaction_id')
    # ### end Alembic commands ###
